
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,19],$V1=[1,18],$V2=[2,11,17],$V3=[1,35],$V4=[1,33],$V5=[1,34],$V6=[1,36],$V7=[1,37],$V8=[1,38],$V9=[1,39],$Va=[2,11,17,18,22,28,29,30,31,32,33,34],$Vb=[2,7,11,17,18,22,26,27,28,29,30,31,32,33,34],$Vc=[1,56],$Vd=[1,57],$Ve=[1,59],$Vf=[1,58],$Vg=[2,11,40,41,42],$Vh=[1,74],$Vi=[1,75],$Vj=[22,45],$Vk=[18,22,41,45];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"inicio":3,"WISON":4,"QUEST_APERTURA":5,"cuerpo":6,"QUEST_CIERRE":7,"EOF":8,"LEX":9,"LLAVE_APERTURA":10,"DOS_PUNTOS":11,"estructura_lexica":12,"LLAVE_CIERRE":13,"SYNTAX_PARSER":14,"estructura_sintactica":15,"produccion_terminal":16,"TERMINAL":17,"ID_TERMINAL":18,"MENOR":19,"MENOS":20,"regla_lexica":21,"PUNTO_COMA":22,"elemento_lexico":23,"unidad_lexica":24,"modificador":25,"KLEENE":26,"MAS":27,"LITERAL_CADENA":28,"PARENT_APERTURA":29,"PARENT_CIERRE":30,"RANGO_NUMERO":31,"RANGO_MINUSCULA":32,"RANGO_MAYUSCULA":33,"RANGO_TOTAL":34,"lista_instrucciones_sintacticas":35,"instruccion_sintactica":36,"non_terminales":37,"sim_inicial":38,"regla_produccion":39,"NO_TERMINAL":40,"ID_NO_TERMINAL":41,"SIMBOLO_INICIAL":42,"IGUAL":43,"lista_alternativas":44,"OR_EXP":45,"cuerpo_produccion":46,"simbolo":47,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON",5:"QUEST_APERTURA",7:"QUEST_CIERRE",8:"EOF",9:"LEX",10:"LLAVE_APERTURA",11:"DOS_PUNTOS",13:"LLAVE_CIERRE",14:"SYNTAX_PARSER",17:"TERMINAL",18:"ID_TERMINAL",19:"MENOR",20:"MENOS",22:"PUNTO_COMA",26:"KLEENE",27:"MAS",28:"LITERAL_CADENA",29:"PARENT_APERTURA",30:"PARENT_CIERRE",31:"RANGO_NUMERO",32:"RANGO_MINUSCULA",33:"RANGO_MAYUSCULA",34:"RANGO_TOTAL",40:"NO_TERMINAL",41:"ID_NO_TERMINAL",42:"SIMBOLO_INICIAL",43:"IGUAL",45:"OR_EXP"},
productions_: [0,[3,6],[3,2],[6,14],[6,3],[12,2],[12,1],[16,6],[16,5],[16,5],[16,2],[16,1],[16,2],[21,2],[21,1],[23,2],[23,1],[25,1],[25,1],[25,1],[24,1],[24,3],[24,1],[24,1],[24,1],[24,1],[24,1],[15,1],[35,2],[35,1],[36,1],[36,1],[36,1],[36,2],[37,3],[38,3],[39,5],[44,3],[44,1],[46,2],[46,1],[47,1],[47,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 
        return $$[$0-3]; 
    
break;
case 2:

        return null; 
    
break;
case 3:

        this.$ = {
            lexico: $$[$0-10],
            sintactico: $$[$0-3]
        };
    
break;
case 4:

        reportarError(yy, {
            descripcion: 'Error en el cuerpo de Wison. Se esperaba: ' + traducirEsperados(['LEX', 'SYNTAX_PARSER']),
            loc: _$[$0-2],
            texto: yytext
        });

        this.$ = { 
                lexico: null, 
                sintactico: null 
        };
    
break;
case 5:

                    $$[$0-1].push($$[$0]);
                    this.$  = $$[$0-1];
                
break;
case 6: case 14:

                    this.$ = [$$[$0]];
                
break;
case 7:


                        this.$ = {
                            tipo: 'TERMINAL',
                            id: $$[$0-4],
                            regla: $$[$0-1]
                        }

                    
break;
case 8:

                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion terminal. Se esperaba: punto y coma.',
                            loc: _$[$0], 
                            texto: $$[$0-4] + " " + $$[$0-3]
                        });

                    
break;
case 9:

                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion terminal. Se esperaba: una expresion regular.',
                            loc: _$[$0-1], 
                            texto: $$[$0-4] + " " + $$[$0-3] + " " + $$[$0-2] + " " + $$[$0-1]
                        });

                    
break;
case 10:

                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion terminal. Se esperaba: la expresion <-.',
                            loc: _$[$0], 
                            texto: $$[$0-1] + " " + $$[$0]
                        });

                    
break;
case 11:

                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion terminal. Se esperaba: el nombre del terminal.',
                            loc: _$[$0], 
                            texto: $$[$0]
                        });

                    
break;
case 12:


                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion terminal. Estructura invalida antes del punto y coma.',
                            loc: _$[$0-1],
                            texto: yytext
                        });
                    
break;
case 13:

                    $$[$0-1].push($$[$0]);
                    this.$ = $$[$0-1];
                
break;
case 15:

                    this.$ = {
                        unidad: $$[$0-1], 
                        modificador: $$[$0]
                        };
                
break;
case 16:

                    this.$ ={
                            unidad: $$[$0], 
                            modificador: null
                        };
                
break;
case 17:

                this.$ = '*';
            
break;
case 18:

                this.$ = '+';
            
break;
case 19:

                this.$ = '?';
            
break;
case 20:

                    this.$ = {
                        tipo: 'CADENA',
                        valor: $$[$0]
                    };
                
break;
case 21:

                    this.$ = {
                        tipo: 'AGRUPACION',
                        contenido: $$[$0-1]
                    };
                
break;
case 22:

                    this.$ = { 
                            tipo: 'REFERENCIA_ID', 
                            valor: $$[$0] 
                    };
                
break;
case 23:

                    this.$ = { 
                            tipo: 'RANGO', 
                            valor: '[0-9]' 
                    };
                
break;
case 24:

                    this.$ = { 
                            tipo: 'RANGO', 
                            valor: '[a-z]' 
                    };
                
break;
case 25:

                    this.$ = { 
                            tipo: 'RANGO', 
                            valor: '[A-Z]' 
                    };
                
break;
case 26:

                    this.$ = { 
                            tipo: 'RANGO', 
                            valor: '[a-zA-Z]' 
                    };
                
break;
case 27:

                                this.$ = $$[$0];
                            
break;
case 28:

                                        $$[$0-1].push($$[$0]); 
                                        this.$ = $$[$0-1];
                                    
break;
case 29:

                                        this.$ = [$$[$0]];
                                    
break;
case 30: case 31: case 32:

                        this.$ = $$[$0];
                    
break;
case 33:

                        this.$ = reportarError(yy, {
                            descripcion: 'Error declaracion sintactica. Estructura invalida antes del punto y coma.',
                            loc: _$[$0-1],
                            texto: yytext
                        });
                    
break;
case 34:

                        this.$ = { 
                                tipo: 'DECLARACION_NO_TERMINAL', 
                                id: $$[$0-1] 
                        };
                    
break;
case 35:

                        this.$ = { 
                                tipo: 'SIMBOLO_INICIAL', 
                            id: $$[$0-1] 
                        };
                    
break;
case 36:

                        this.$ = {
                            tipo: 'PRODUCCION',
                            padre: $$[$0-4],
                            alternativas: $$[$0-1]
                        };
                    
break;
case 37:

                        $$[$0-2].push($$[$0]);
                        this.$ = $$[$0-2];
                    
break;
case 38: case 40:

                        this.$ = [$$[$0]];
                    
break;
case 39:

                        $$[$0-1].push($$[$0]);
                        this.$ = $$[$0-1];
                    
break;
case 41:

                this.$ = { 
                        tipo: 'TERMINAL', 
                        valor: $$[$0] 
                };
            
break;
case 42:

                this.$ = { 
                        tipo: 'NO_TERMINAL', 
                        valor: $$[$0] 
                };
            
break;
}
},
table: [{2:[1,3],3:1,4:[1,2]},{1:[3]},{5:[1,4]},{8:[1,5]},{2:[1,8],6:6,9:[1,7]},{1:[2,2]},{7:[1,9]},{10:[1,10]},{13:[1,11]},{4:[1,12]},{11:[1,13]},{13:[1,14]},{8:[1,15]},{2:$V0,12:16,16:17,17:$V1},{7:[2,4]},{1:[2,1]},{2:$V0,11:[1,20],16:21,17:$V1},o($V2,[2,6]),o($V2,[2,11],{18:[1,22]}),{22:[1,23]},{13:[1,24]},o($V2,[2,5]),o($V2,[2,10],{19:[1,25]}),o($V2,[2,12]),{14:[1,26]},{20:[1,27]},{10:[1,28]},{18:$V3,21:29,22:[1,30],23:31,24:32,28:$V4,29:$V5,31:$V6,32:$V7,33:$V8,34:$V9},{10:[1,40]},o($V2,[2,8],{24:32,23:42,18:$V3,22:[1,41],28:$V4,29:$V5,31:$V6,32:$V7,33:$V8,34:$V9}),o($V2,[2,9]),o($Va,[2,14]),o($Va,[2,16],{25:43,7:[1,46],26:[1,44],27:[1,45]}),o($Vb,[2,20]),{18:$V3,21:47,23:31,24:32,28:$V4,29:$V5,31:$V6,32:$V7,33:$V8,34:$V9},o($Vb,[2,22]),o($Vb,[2,23]),o($Vb,[2,24]),o($Vb,[2,25]),o($Vb,[2,26]),{11:[1,48]},o($V2,[2,7]),o($Va,[2,13]),o($Va,[2,15]),o($Va,[2,17]),o($Va,[2,18]),o($Va,[2,19]),{18:$V3,23:42,24:32,28:$V4,29:$V5,30:[1,49],31:$V6,32:$V7,33:$V8,34:$V9},{2:$Vc,15:50,35:51,36:52,37:53,38:54,39:55,40:$Vd,41:$Ve,42:$Vf},o($Vb,[2,21]),{11:[1,60]},{2:$Vc,11:[2,27],36:61,37:53,38:54,39:55,40:$Vd,41:$Ve,42:$Vf},o($Vg,[2,29]),o($Vg,[2,30]),o($Vg,[2,31]),o($Vg,[2,32]),{22:[1,62]},{41:[1,63]},{41:[1,64]},{19:[1,65]},{13:[1,66]},o($Vg,[2,28]),o($Vg,[2,33]),{22:[1,67]},{22:[1,68]},{43:[1,69]},{13:[1,70]},o($Vg,[2,34]),o($Vg,[2,35]),{18:$Vh,41:$Vi,44:71,46:72,47:73},{7:[2,3]},{22:[1,76],45:[1,77]},o($Vj,[2,38],{47:78,18:$Vh,41:$Vi}),o($Vk,[2,40]),o($Vk,[2,41]),o($Vk,[2,42]),o($Vg,[2,36]),{18:$Vh,41:$Vi,46:79,47:73},o($Vk,[2,39]),o($Vj,[2,37],{47:78,18:$Vh,41:$Vi})],
defaultActions: {5:[2,2],14:[2,4],15:[2,1],70:[2,3]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};

    /* Diccionario para traducir tokens técnicos a nombres amigables */
    const diccionarioTokens = {
        "PUNTO_COMA": "';'",
        "LLAVE_APERTURA": "'{'",
        "LLAVE_CIERRE": "'}'",
        "CORCHETE_APERTURA": "'['",
        "CORCHETE_CIERRE": "']'",
        "DOS_PUNTOS": "':'",
        "ID_TERMINAL": "identificador de terminal",
        "ID_NO_TERMINAL": "identificador de no terminal",
        "LEX": "la palabra reservada 'Lex'",
        "SYNTAX_PARSER": "la secciAn 'Syntax'",
        "EOF": "el fin del archivo"
    };

    /* Función auxiliar para reportar errores al arreglo global */
    function reportarError(yy, info) {
        const nuevoError = {
            tipo: 'ERROR_SINTACTICO',
            descripcion: info.descripcion,
            fila: info.loc.first_line,
            columna: info.loc.first_column + 1
        };
    
        yy.errores.push({
            lexema: info.texto || "N/A",
            tipo: "Sintactico",
            fila: nuevoError.fila,
            columna: nuevoError.columna,
            descripcion: nuevoError.descripcion
        });
    
        return nuevoError;
    } 

    /* Función auxiliar para traducir los tokens esperados que Jison provee */
    function traducirEsperados(esperados) {

        if (!esperados || esperados.length === 0) return "algo diferente";

        const traducidos = esperados.map(token => {
            const tokenLimpio = token.replace(/'/g, "");
            return diccionarioTokens[tokenLimpio] || tokenLimpio;
        });

        if (traducidos.length > 1) {
            const ultimo = traducidos.pop();
            return traducidos.join(", ") + " o " + ultimo;
        }
        return traducidos[0];
    }
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"ranges":true,"yylineno":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignorar espacios */
break;
case 1:/* Ignorar caracteres basura */
break;
case 2:/*Ignorar comentario de linea*/
break;
case 3:/*Ignorar comentario multilinea*/ 
break;
case 4:return 31;
break;
case 5:return 32;
break;
case 6:return 33;
break;
case 7:return 34;
break;
case 8:return 4;
break;
case 9:return 9;
break;
case 10:return 17;
break;
case 11:return 40;
break;
case 12:return 14;
break;
case 13:return 42;
break;
case 14:return 29;
break;
case 15:return 30;
break;
case 16:return 10;
break;
case 17:return 13;
break;
case 18:return 'CORCHETE_APERTURA';
break;
case 19:return 'CORCHETE_CIERRE';
break;
case 20:return 11;
break;
case 21:return 19;
break;
case 22:return 22;
break;
case 23:return 45;
break;
case 24:return 20;
break;
case 25:return 27;
break;
case 26:return 26;
break;
case 27:return 5;
break;
case 28:return 7;
break;
case 29:return 18;
break;
case 30:return 41;
break;
case 31: 
                        yy_.yytext = yy_.yytext.slice(1, -1); 
                        return 28; 
                        
break;
case 32:return 43;
break;
case 33:
                                if (!yy.errores) yy.errores = [];
                                
                                yy.errores.push({
                                    lexema: yy_.yytext,
                                    tipo: "Lexico",
                                    fila: yy_.yylloc.first_line,
                                    columna: yy_.yylloc.first_column + 1,
                                    descripcion: "Caracter no valido en el lenguaje"
                                });
                            
break;
case 34:return 8;
break;
}
},
rules: [/^(?:\s+)/,/^(?:[\u200B\uFEFF\u200E\u200F\u202A-\u202E]+)/,/^(?:#.*)/,/^(?:\/\*\*([^*]|\*+[^*/])*(\*+\/))/,/^(?:\[0-9\])/,/^(?:\[a-z\])/,/^(?:\[A-Z\])/,/^(?:\[aA-zZ\])/,/^(?:Wison\b)/,/^(?:Lex\b)/,/^(?:Terminal\b)/,/^(?:No_Terminal\b)/,/^(?:Syntax\b)/,/^(?:Initial_Sim\b)/,/^(?:\()/,/^(?:\))/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?::)/,/^(?:<)/,/^(?:;)/,/^(?:\|)/,/^(?:-)/,/^(?:\+)/,/^(?:\*)/,/^(?:¿)/,/^(?:\?)/,/^(?:\$_[a-zA-Z0-9_]+)/,/^(?:%_[a-zA-Z0-9_]+)/,/^(?:'[^']*')/,/^(?:=)/,/^(?:.)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}
export const parse = (input) => parser.parse(input);
export default parser;
